version: '3.8'

services:
  bot:
    build: .
    container_name: discord-forum-bot
    restart: unless-stopped
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - STAFF_CSV_PATH=/app/staff.csv
      - PORT=${PORT}
      - MYSQL_DATABASE=forum
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - RUN_MODE=watch
      - EXIT_AFTER_SYNC=false
      - REGISTER_COMMANDS=false
      - ENABLE_HISTORICAL_SYNC=${ENABLE_HISTORICAL_SYNC}
      - FORCE_FULL_SYNC=${FORCE_FULL_SYNC}
      - SYNC_GUILD_ID=${SYNC_GUILD_ID}
      - SYNC_CHANNEL_ID=${SYNC_CHANNEL_ID}
      - SYNC_LIMIT=1
      - SYNC_SKIP_EXISTING=true
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./staff.csv:/app/staff.csv:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3008/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
